version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3006:3006m
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/baimin/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/baimin/redis-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
